const maleCandidates = [
    { id: 1, imageUrl: 'MALE_PROFILE_1', properties: { strength: 7, intelligence: 5, kindness: 6, humor: 8, creativity: 4 }, lookingFor: { kindness: 7, intelligence: 6 } },
    { id: 2, imageUrl: 'MALE_PROFILE_2', properties: { strength: 4, intelligence: 8, kindness: 5, humor: 3, creativity: 7 }, lookingFor: { creativity: 6, humor: 4 } },
    { id: 3, imageUrl: 'MALE_PROFILE_3', properties: { strength: 6, intelligence: 9, kindness: 4, humor: 2, creativity: 5 }, lookingFor: { intelligence: 8, creativity: 4 } },
    { id: 4, imageUrl: 'MALE_PROFILE_4', properties: { strength: 9, intelligence: 6, kindness: 7, humor: 5, creativity: 3 }, lookingFor: { strength: 8, kindness: 6 } },
    { id: 5, imageUrl: 'MALE_PROFILE_5', properties: { strength: 3, intelligence: 7, kindness: 8, humor: 4, creativity: 9 }, lookingFor: { humor: 5, creativity: 7 } },
    { id: 6, imageUrl: 'MALE_PROFILE_6', properties: { strength: 8, intelligence: 4, kindness: 9, humor: 7, creativity: 2 }, lookingFor: { kindness: 8, strength: 5 } },
    { id: 7, imageUrl: 'MALE_PROFILE_7', properties: { strength: 5, intelligence: 5, kindness: 6, humor: 6, creativity: 5 }, lookingFor: { intelligence: 4, kindness: 5 } },
    { id: 8, imageUrl: 'MALE_PROFILE_8', properties: { strength: 4, intelligence: 6, kindness: 7, humor: 3, creativity: 8 }, lookingFor: { creativity: 7, intelligence: 5 } },
    { id: 9, imageUrl: 'MALE_PROFILE_9', properties: { strength: 2, intelligence: 7, kindness: 5, humor: 9, creativity: 6 }, lookingFor: { humor: 8, kindness: 4 } },
    { id: 10, imageUrl: 'MALE_PROFILE_10', properties: { strength: 6, intelligence: 8, kindness: 4, humor: 5, creativity: 7 }, lookingFor: { strength: 5, intelligence: 7 } },
    { id: 11, imageUrl: 'MALE_PROFILE_11', properties: { strength: 7, intelligence: 4, kindness: 8, humor: 6, creativity: 3 }, lookingFor: { kindness: 7, humor: 5 } },
    { id: 12, imageUrl: 'MALE_PROFILE_12', properties: { strength: 3, intelligence: 9, kindness: 5, humor: 4, creativity: 8 }, lookingFor: { creativity: 6, intelligence: 8 } },
    { id: 13, imageUrl: 'MALE_PROFILE_13', properties: { strength: 8, intelligence: 6, kindness: 7, humor: 2, creativity: 5 }, lookingFor: { strength: 6, kindness: 5 } },
    { id: 14, imageUrl: 'MALE_PROFILE_14', properties: { strength: 5, intelligence: 7, kindness: 9, humor: 3, creativity: 4 }, lookingFor: { humor: 4, kindness: 8 } },
    { id: 15, imageUrl: 'MALE_PROFILE_15', properties: { strength: 6, intelligence: 5, kindness: 4, humor: 7, creativity: 8 }, lookingFor: { intelligence: 4, creativity: 7 } },
    { id: 16, properties: { strength: 9, intelligence: 3, kindness: 6, humor: 8, creativity: 2 }, lookingFor: { strength: 8, humor: 7 } },
    { id: 17, properties: { strength: 4, intelligence: 8, kindness: 5, humor: 9, creativity: 3 }, lookingFor: { creativity: 4, intelligence: 7 } },
    { id: 18, properties: { strength: 2, intelligence: 6, kindness: 8, humor: 4, creativity: 7 }, lookingFor: { kindness: 7, creativity: 5 } },
    { id: 19, properties: { strength: 4, intelligence: 7, kindness: 3, humor: 8, creativity: 4 }, lookingFor: { intelligence: 6, strength: 7 } },
    { id: 20, properties: { strength: 7, intelligence: 6, kindness: 4, humor: 6, creativity: 8 }, lookingFor: { strength: 6, humor: 5 } },
];

const femaleCandidates = [
    { id: 1, imageUrl: 'FEMALE_PROFILE_1', properties: { strength: 4, intelligence: 7, kindness: 8, humor: 6, creativity: 5 }, lookingFor: { strength: 5, intelligence: 6 } },
    { id: 2, imageUrl: 'FEMALE_PROFILE_2', properties: { strength: 6, intelligence: 5, kindness: 9, humor: 4, creativity: 7 }, lookingFor: { kindness: 8, humor: 5 } },
    { id: 3, imageUrl: 'FEMALE_PROFILE_3', properties: { strength: 3, intelligence: 8, kindness: 7, humor: 5, creativity: 6 }, lookingFor: { intelligence: 7, creativity: 4 } },
    { id: 4, imageUrl: 'FEMALE_PROFILE_4', properties: { strength: 7, intelligence: 6, kindness: 5, humor: 8, creativity: 4 }, lookingFor: { humor: 7, kindness: 6 } },
    { id: 5, imageUrl: 'FEMALE_PROFILE_5', properties: { strength: 5, intelligence: 4, kindness: 6, humor: 9, creativity: 8 }, lookingFor: { creativity: 7, humor: 6 } },
    { id: 6, imageUrl: 'FEMALE_PROFILE_6', properties: { strength: 8, intelligence: 3, kindness: 4, humor: 7, creativity: 5 }, lookingFor: { strength: 7, intelligence: 4 } },
    { id: 7, imageUrl: 'FEMALE_PROFILE_7', properties: { strength: 4, intelligence: 9, kindness: 5, humor: 6, creativity: 7 }, lookingFor: { intelligence: 8, creativity: 6 } },
    { id: 8, imageUrl: 'FEMALE_PROFILE_8', properties: { strength: 5, intelligence: 6, kindness: 7, humor: 3, creativity: 8 }, lookingFor: { creativity: 7, kindness: 5 } },
    { id: 9, imageUrl: 'FEMALE_PROFILE_9', properties: { strength: 6, intelligence: 5, kindness: 4, humor: 9, creativity: 3 }, lookingFor: { humor: 8, strength: 5 } },
    { id: 10, imageUrl: 'FEMALE_PROFILE_10', properties: { strength: 7, intelligence: 8, kindness: 6, humor: 4, creativity: 5 }, lookingFor: { strength: 6, intelligence: 7 } },
    { id: 11, imageUrl: 'FEMALE_PROFILE_11', properties: { strength: 3, intelligence: 6, kindness: 8, humor: 5, creativity: 9 }, lookingFor: { kindness: 7, creativity: 8 } },
    { id: 12, imageUrl: 'FEMALE_PROFILE_12', properties: { strength: 5, intelligence: 7, kindness: 4, humor: 8, creativity: 6 }, lookingFor: { humor: 7, intelligence: 6 } },
    { id: 13, imageUrl: 'FEMALE_PROFILE_13', properties: { strength: 8, intelligence: 4, kindness: 7, humor: 6, creativity: 5 }, lookingFor: { strength: 7, kindness: 6 } },
    { id: 14, imageUrl: 'FEMALE_PROFILE_14', properties: { strength: 6, intelligence: 9, kindness: 5, humor: 4, creativity: 3 }, lookingFor: { intelligence: 8, humor: 4 } },
    { id: 15, imageUrl: 'FEMALE_PROFILE_15', properties: { strength: 7, intelligence: 3, kindness: 6, humor: 5, creativity: 8 }, lookingFor: { creativity: 7, strength: 6 } },
    { id: 16, properties: { strength: 4, intelligence: 8, kindness: 7, humor: 6, creativity: 4 }, lookingFor: { humor: 5, intelligence: 7 } },
    { id: 17, properties: { strength: 5, intelligence: 7, kindness: 4, humor: 8, creativity: 6 }, lookingFor: { humor: 7, intelligence: 6 } },
    { id: 18, properties: { strength: 6, intelligence: 4, kindness: 9, humor: 3, creativity: 5 }, lookingFor: { kindness: 8, creativity: 4 } },
    { id: 19, properties: { strength: 7, intelligence: 6, kindness: 5, humor: 9, creativity: 7 }, lookingFor: { humor: 8, strength: 4 } },
    { id: 20, properties: { strength: 6, intelligence: 5, kindness: 4, humor: 5, creativity: 3 }, lookingFor: { strength: 7, intelligence: 6 } },
];
